require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Define find-and-replace function
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
    text = File.read(name)
    replace = text.gsub(findstr,replacestr)
    replaced = text.index(replacestr)
    if replaced == nil && text != replace
      puts "Fix: " + name
      File.chmod(0775, name)
      File.open(name, "w") { |file| file.puts replace }
      STDOUT.flush
    end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

target 'Ressista' do
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'GoogleMaps'

  pod 'Google-Maps-iOS-Utils'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'


  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'


  target 'RessistaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)

    # fix for Flipper-Folly on IOS 14.5
    find_and_replace("Pods/Flipper-Folly/folly/synchronization/DistributedMutex-inl.h", "atomic_notify_one(state)", "folly::atomic_notify_one(state)")
    find_and_replace("Pods/Flipper-Folly/folly/synchronization/DistributedMutex-inl.h", "atomic_wait_until(&state, previous | data, deadline)", "folly::atomic_wait_until(&state, previous | data, deadline)")
  end
end

target 'Ressista-tvOS' do
  # Pods for Ressista-tvOS

  target 'Ressista-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
