require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Ressista' do
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'GoogleMaps'

  pod 'Google-Maps-iOS-Utils'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'


  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'


  target 'RessistaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Ressista-tvOS' do
  # Pods for Ressista-tvOS

  target 'Ressista-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
